# Generated by Django 5.1.5 on 2025-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=20)),
                ('lesson', models.CharField(max_length=50)),
            ],
        ),
    ]
