# Generated by Django 5.1.5 on 2025-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='homework',
            field=models.TextField(blank=True, null=True),
        ),
    ]
