# Generated by Django 5.1.5 on 2025-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lesson_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
