# Generated by Django 5.1.5 on 2025-03-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schedule_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
