# Generated by Django 5.1.5 on 2025-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_schedule_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
