# Generated by Django 5.2.6 on 2025-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appeal_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='coordinates',
            field=models.JSONField(default=list, help_text='Формат: [широта, долгота]'),
        ),
    ]
