# Generated by Django 5.2.7 on 2025-10-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_camera_chatthread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.JSONField(default=list, help_text='Список id детекторов (pk)')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('vehicle_count', models.IntegerField(default=0)),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True)),
                ('avg_travel_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='app.detector')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle_id', 'timestamp'], name='app_vehicle_vehicle_8d5f66_idx'), models.Index(fields=['detector', 'timestamp'], name='app_vehicle_detecto_f67b25_idx')],
            },
        ),
    ]
