# Generated by Django 5.2.7 on 2025-10-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_accidentstatistics_accidenttype_detector_roadworks_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AccidentStatistics',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('total_accidents', models.IntegerField(default=0)),
                        ('injured', models.IntegerField(default=0)),
                        ('killed', models.IntegerField(default=0)),
                        ('year', models.IntegerField(default=2024)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AccidentType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('color', models.CharField(default='#36A2EB', help_text='Hex цвет для графика', max_length=7)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RoadWorks',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('count', models.IntegerField(default=0)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='TrafficForecast',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('speed', models.IntegerField(help_text='Скорость в км/ч')),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='WeatherData',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('temperature', models.IntegerField()),
                        ('description', models.CharField(max_length=100)),
                        ('icon', models.CharField(default='fa-sun', max_length=50)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AccidentData',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')])),
                        ('year', models.IntegerField(default=2024)),
                        ('count', models.IntegerField(default=0)),
                        ('accident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_data', to='app.accidenttype')),
                    ],
                    options={
                        'unique_together': {('accident_type', 'month', 'year')},
                    },
                ),
            ],
        ),
    ]
